services:
  - type: web
    name: ytscript
    runtime: static
    staticPublishPath: ./public
    buildCommand: ""
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
